### ISSUE TITLE
Channel exceptions should be reported as such

### ISSUE THREAD

**Issue by ehongyu** [videlalvaro/php-amqplib#290] opened 2015-07-01 02:46 UTC
After I tried to fetch a message from a  non-existent queue using basic_consume or basic_get, I found the connection of the channel is nulled. I am wondering whether anybody else has seen this issue. The error message is like

PHP Fatal error:  Call to a member function send_channel_method_frame() on a non-object in /mypath/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php on line 223

**Comment by michaelklishin** [comment] 2015-07-01 11:23
Yes, this expected: this is how the protocol works.

**Comment by mfreedman** [comment] 2015-07-29 17:50
We're also seeing this on a non-existent exchange.

**Comment by snellingio** [comment] 2015-07-29 17:50
+1

**Comment by michaelklishin** [comment] 2015-07-29 19:24
What are your expectations? This is expected behaviour and how the protocol works: using non-existent entities results in a channel exception and closes the channel. With any client.

The only thing that can change here is the error message that this client reports.

**Comment by mfreedman** [comment] 2015-07-29 20:06
This isn't a channel exception.  This is a fatal error.

**Comment by videlalvaro** [comment] 2015-08-11 15:11
1) Can you reproduce this with latest master.
2) Can you provide some code to reproduce the issue? I tried publishing to a non existing exchange, and also doing a `basic_get` to a non existing queue and I get a `AMQPProtocolChannelException` being thrown

**Comment by mfreedman** [comment] 2015-08-11 20:46
I can't seem to reproduce the fatal error now.   I did stumble on to this when publishing to a non-existent queue:

Warning: array_push() expects parameter 1 to be array, null given in /vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php on line 582

**Comment by videlalvaro** [comment] 2015-08-11 21:12
I will investigate that other error. Seems to be  related to a channel that's not destroyed properly after the exception happens.

**Comment by ehongyu** [comment] 2015-08-12 04:41
Not seeing the original error either. Thanks.

**Comment by videlalvaro** [comment] 2015-09-22 23:28
The warning should be fixed here https://github.com/videlalvaro/php-amqplib/commit/f4dd87a9e7398ed213bce6b56d77556e4f9378ab

**Closed by videlalvaro** 2015-09-22 23:28 UTC
