### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by fixedd** [videlalvaro/php-amqplib#261] opened 2015-03-27 14:00 UTC
Our script is dying with a Segmentation Fault in some cases (but not all). It *seems* to happen in executions of our script which cause a very high number (a few thousand) of messages to be delivered into our queue and it's 100% reproducable with those sets of data.  I don't really know how to work with GDB, but I was able to get the following out of it:

> #0  zend_std_get_method (object_ptr=0x2959ac0, method_name=0x1f425e0 "connectionClose", method_len=15) at /build/buildd/php5-5.3.10/Zend/zend_object_handlers.c:847
847	/build/buildd/php5-5.3.10/Zend/zend_object_handlers.c: No such file or directory.

`connectionClose()` is called by AbstractConnection's `close()`method. I tried adding some more sanity checks, such as changing 

    if (!$this->protocolWriter || !$this->isConnected()) {

to 

    if (!$this->protocolWriter || !$this->isConnected() || !is_object($this->protocolWriter) || !method_exists($this->protocolWriter, 'connectionClose')) {

to no avail.  I'm not really sure what GDB is telling me the problem is, so I'm not really sure of the right way to address it.  Immediately returning null from the `close` method has solved our problem in the short-term, but I fear this will end up causing more problems than it solves.

**Comment by michaelklishin** [comment] 2015-03-27 16:09
This library has no native code. The root cause of your segmentation faults is thus somewhere else, perhaps in the runtime.

**Comment by frankmayer** [comment] 2015-03-27 16:14
@fixedd the path in your report suggests that you are using a pretty outdated php build (php5-5.3.10). Have you tried this with something newer?

**Comment by fixedd** [comment] 2015-03-27 16:35
@frankmayer Sorry, I meant to mention... I tried it on a bunch of versions, the most recent being 5.5.9.

**Comment by frankmayer** [comment] 2015-03-27 16:52
@fixedd maybe you're dealing with some kind of obscure zend bug. Unfortunately, even, for example, with PHP 5.5.9 you're using an outdated version of the 5.5 version, which could still have some bug that may or may not already be fixed.

One other thing that comes to mind, since you're mentioning a very high number of messages, is, that you may be reaching the limit of file descriptors / open files in your system, which may cause php to fail.

**Comment by fixedd** [comment] 2015-03-27 16:58
@frankmayer The limit thing had occurred to me too, but does that make sense since it's only on the closing call that it dies?

**Comment by matteosister** [comment] 2015-03-27 17:12
it happend also to us....we are trying to upgrade a symfony2 project to latest version of RabbitMQBundle. The problems comes from the version of this library...could you please try with the [version v2.2.6](https://github.com/videlalvaro/php-amqplib/releases/tag/v2.2.6) and see if works?

**Comment by frankmayer** [comment] 2015-03-27 17:46
It could be the limit thing. connectionClose() seems to create a new AMQPWriter and writes to the *existing* socket, before closing. This should theoretically not be an issue. I 'm just saying that it could, and may be worth a try (along with using the latest php builds, maybe even 5.6.x)), in order to narrow down the source of the problem.
Has this been tested with both streamIO and socketIO?

**Comment by matteosister** [comment] 2015-03-27 20:08
For us the php version is irrelevant. I tried with the latest minor of 5.5 and 5.6...we are using docker so it's easy...

**Comment by Metabor** [comment] 2015-04-08 08:07
We have the same problem, when using this library  (with PHP 5.5.9 on Ubuntu and also on windows with PHP 5.5.21).
I think that there somewhere is a recursive loop that got infinite:
http://stackoverflow.com/questions/7327393/why-does-an-infinitely-recursive-function-in-php-cause-a-segfault

**Comment by Metabor** [comment] 2015-04-08 10:35
"could you please try with the version v2.2.6 and see if works?"
I was trying it with this version and it worked.
So I checked version 2.4.0, but this version has also this issue for me.
Will now check 2.3.0 to see if the issue is there, too.

**Comment by Metabor** [comment] 2015-04-08 11:52
Version 2.3.0 did also not have this issue.
It seems that the issue is there since version 2.4.0.
Maybe I can help with this information.

**Comment by Metabor** [comment] 2015-04-08 14:00
We updated the server to PHP 5.6.7 and had to remove XHProf extension (because it was no available for that version).
Now the issue is gone also in the actual version 2.5.0.
Not sure if updating to PHP 5.6.7 helped or if XHProf was the root for that problem.

**Comment by frankmayer** [comment] 2015-04-09 14:06
@Metabor 
Any chance to test this against the prior PHP version you were running, but with XHProf removed?

**Comment by matteosister** [comment] 2015-04-09 17:17
@frankmayer FYI I don't have xhprof and I got the problem anyway....

**Comment by fixedd** [comment] 2015-04-09 17:42
Same here, we don't use xhprof.

**Comment by frankmayer** [comment] 2015-04-09 19:17
Could some xdebug or other extension be conflicting? Maybe it would help to compare phpinfo() outputs (having removed all sensitive information) where the problem was found?

**Comment by arduanov** [comment] 2015-04-28 12:57
I have same problem when testing own symfony application
Version 2.3.0 works fine

**Comment by videlalvaro** [comment] 2015-04-28 14:43
I understand this happens. It would be nice if someone having the issue could try to pin point what's going on.

@fixedd could you provide a simple gist with a script to reproduce, so I can try to find a solution?

**Comment by arduanov** [comment] 2015-04-28 19:21
Segmentation fault script

```
require_once(__DIR__ . '/../vendor/autoload.php');

use PhpAmqpLib\Connection\AMQPStreamConnection;

$config =
    [
        'host' => 'localhost',
        'port' => 5672,
        'user' => 'guest',
        'password' => 'guest',
    ];

function getConnection($config_amqp)
{
    return new AMQPStreamConnection($config_amqp['host'], $config_amqp['port'], $config_amqp['user'], $config_amqp['password']);
}

for ($i = 0; $i < 1000; $i++) {
    $conn = getConnection($config);
}
```

**Comment by videlalvaro** [comment] 2015-04-28 23:34
@arduanov besides that I have to try this, what's the real world usage of creating so many connections?

**Comment by fixedd** [comment] 2015-04-28 23:59
Sorry, I've been unresponsive... been on vacation and only returned today.

@videlalvaro We use rabbit as a sort of message bus. Sometimes an event will need to queue a message for many different services on many different servers. It isn't common for us to run into the magic limit, but there's certain data imports we do occasionally which end up firing of LOTS of messages... this is what alerted us to the issue.

**Comment by arduanov** [comment] 2015-04-29 05:11
This is real usage in PHPUnit tests

**Comment by matteosister** [comment] 2015-04-29 06:13
@videlalvaro it happens only in unit test for us. In production we don't have as many connection, so no problem at all. But not being able to run our test suite is keeping us from upgrade.

**Comment by videlalvaro** [comment] 2015-04-29 09:48
@matteosister do you have problems with the unit tests because you have low memory for RabbitMQ or PHP? I'm just trying to narrow down how to reproduce this. I can run the unit test on my mac for example without problems

**Comment by arduanov** [comment] 2015-04-29 14:07
I run sample script in php-cli

my environment:
virtualbox with ubuntu 12.04
ram 1 gigabyte
php memory_limit 128M
rabbitmq memory by default

**Comment by matteosister** [comment] 2015-04-29 15:23
@videlalvaro I'm on ubuntu too and I run my tests in docker. The memory for php is very high...for rabbit I'm using the [pivotal docker image](https://registry.hub.docker.com/_/rabbitmq/)
I still haven't tried with the @arduanov script...gonna try it asap

**Comment by matteosister** [comment] 2015-04-29 16:16
@videlalvaro I confirm the issue

I created a repo to reproduce it with docker https://github.com/matteosister/amqp-test

**Comment by videlalvaro** [comment] 2015-04-29 16:27
@matteosister thanks for the repo.

As I said earlier, I don't doubt this happens, in fact, I've seen it on a Linux VM already and @arduanov tests allows me to reproduce it.

What I would like to know, is if this happens due to some flow control/block command sent from rabbit, or just because the php library allocates too many instances of certain objects for example

**Comment by matteosister** [comment] 2015-05-04 17:45
@videlalvaro I don't know how to check the dump...I'm not into this kind of things at all...let me know if I can help in some way...

**Comment by kasl** [comment] 2015-05-05 08:09
I am also got a segmentation fault on the local machine, after sending a large of number of messages in the queue, and then php crashed:
![log1](https://cloud.githubusercontent.com/assets/3302886/7468955/34fa40e0-f330-11e4-8037-cb9bb2ac7ec6.png)
![log2](https://cloud.githubusercontent.com/assets/3302886/7468961/3dc471aa-f330-11e4-80ae-302c1fd5832d.png)
maybe it will help

**Comment by odiel** [comment] 2015-05-05 17:16
I have the exact same issue when running Unit Tests.

I have noticed this since long time ago:

    /**
     * @param \PhpAmqpLib\Connection\AbstractConnection $connection
     * @param string $channel_id
     */
    public function __construct(AbstractConnection $connection, $channel_id)
    {
        $this->connection = $connection;
        $this->channel_id = $channel_id;
        $connection->channels[$channel_id] = $this; <- this is creating an object self reference, IMO not good at all.

I guess PHPUnit is crashing because the object self reference.

**Comment by matteosister** [comment] 2015-05-05 20:11
@odiel thanks for your suggestion! Do you have a gist or something?

**Comment by peelandsee** [comment] 2015-05-26 17:56
we run into the same problem in production.. we'll revert to 2.3.

**Comment by mikefox** [comment] 2015-06-10 15:29
We're running into the same issue when running Behat test. Still trying to find a workaround.

**Comment by matteosister** [comment] 2015-06-10 19:50
same here...I'm on symfony and I'm trying to mock the connection to entirely shut down rabbit in the test environment. @videlalvaro do you have any idea on how to easily achieve this?

**Comment by mikefox** [comment] 2015-06-12 15:49
Fixed it by disabling PHP's internal garbage collector when running test suite:
`ini_set('zend.enable_gc', 0);`

**Comment by matteosister** [comment] 2015-06-13 12:29
@mikefox thank you very much! Works for me too...

**Comment by matts2cant** [comment] 2015-07-07 16:43
Hi guys, i stumbles upon this issue today and the following code in my behat Context file seams to fix the issue:

```php
/**
 * @AfterScenario
 */
public function closeAmqpConnection()
{
    $connection = $this->getContainer()->get('old_sound_rabbit_mq.connection.default');
    if ($connection->isConnected()) {
        $connection->close();
    }
}
```

Hope this helps !

**Comment by EddyLane** [comment] 2015-07-13 14:51
Thanks, both @mikefox and @matts2cant solutions worked for my Behat tests. I'm going with Matts as seems a little cleaner.

**Comment by michaelklishin** [comment] 2015-07-29 20:10
Closing as pure PHP library cannot be held responsible for segmentation faults.

**Closed by michaelklishin** 2015-07-29 20:10 UTC

**Comment by c-datculescu** [comment] 2015-09-14 09:41
Hello.

We ran into a similar issue. We were recreating connections in a loop, and this crashed with segmentation fault.

We fixed it by implementing a destruct method that closes the channels and the connections and this fixed our problem.

Best,
Cristian.

**Comment by feridmovsumov** [comment] 2015-10-06 07:12
I solved this problem by closing channel and connection

```php
$producer = $this->container->get('old_sound_rabbit_mq.webhook_producer');
...
$producer->getChannel()->getConnection()->close();
$producer->getChannel()->close();
```

**Comment by LeoBenoist** [comment] 2015-11-12 16:32
same problem

**Comment by michaelklishin** [comment] 2015-11-12 17:06
I have a feeling that with 1K connections some environments will run out of file descriptors available to the process: it's 256 on OS X and 1024 on Linux (both values are absolutely inadequate for servers or test suites that open thousands of connections).

**Comment by LeoBenoist** [comment] 2015-11-13 08:15
In our case it happened when: running behat (only with symfony collector and profiler activated) and the producer is instantiate and not use for anything (injected in a subscriber service).

Indeed if I do @feridmovsumov solution it works. But I run into exceptions if I try to reopen the connection later.

**Comment by lightster** [comment] 2016-05-30 03:58
I've run into this issue multiple times with phpunit + php-amqplib, so I reported a bug to PHP: https://bugs.php.net/bug.php?id=72286

The underlying PHP issue is reproduced in this smaller test case: https://github.com/lightster/php-circular-reference-segfault/blob/master/segfault.php

@postalservice14 and/or @nubeiro: are you interested in working around the PHP bug? I can look into seeing what amount of code would need to change in order to avoid this issue.

**Comment by zerkms** [comment] 2016-06-28 00:03
> Closing as pure PHP library cannot be held responsible for segmentation faults.

Actually that is only partially true.

The typical code to retrieve the channel looks like

```php
    private function getClient(array $config)
    {
        $credentials = $config['credentials'];

        $conn = new AMQPStreamConnection($credentials['host'], $credentials['port'], $credentials['username'], $credentials['password'], '/');
        $ch = $conn->channel();
        $ch->basic_qos(null, 1, null);

        return $ch;
    }
```

And in this case the `$conn` reference is not hold by anything, so it is garbage collected. And then the channel tries to read from the socket.

So it's library's responsibility as well to not make resources it still relies on garbage-collectible.

**Comment by andreyrevinate** [comment] 2016-07-05 17:13
I think I have a tweak that fixes this issue. Please try this: https://github.com/php-amqplib/php-amqplib/pull/419

**Comment by LeoBenoist** [comment] 2016-08-12 15:00
I don't have the issue anymore in php7

**Comment by konstantinnikiforov** [comment] 2018-10-15 03:11
> I don't have the issue anymore in php7

Is it confirmed working in php 7.0 or 7.1?
